version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
  user-service:
    build: ./user-service
    ports:
      - "8082:8082"
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"