apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consul
      component: server
  template:
    metadata:
      labels:
        app: consul
        component: server
    spec:
      containers:
        - name: consul
          image: consul:1.15
          ports:
            - containerPort: 8500
            - containerPort: 8300
            - containerPort: 8301
          env:
            - name: CONSUL_LOCAL_CONFIG
              value: |
                {
                  "datacenter": "dc1",
                  "server": true,
                  "bootstrap_expect": 3,
                  "client_addr": "0.0.0.0"
                }
          volumeMounts:
            - name: config
              mountPath: /consul/config
      volumes:
        - name: config
          configMap:
            name: consul-config