apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: consul
          image: consul:latest
          ports:
            - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  ports:
    - port: 8500
  selector:
    app: consul