apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: course-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb:27017/courses"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  type: ClusterIP
  selector:
    app: course-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083