apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
data:
  logstash.conf: |
    input {
      tcp {
        port => 5044
        codec => json
      }
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
      }
    }